env:
  - GO111MODULE=on
  - CGO_ENABLED=0
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  - id: "ttctl"
    binary: ttctl
    main: cmd/ttctl/main.go
    ldflags:
      - -s -w -X github.com/Slahser/coup-de-grace/pkg/version.gitVersion={{ .Version }} -X github.com/Slahser/coup-de-grace/pkg/version.gitCommit={{ .ShortCommit }} -X github.com/Slahser/coup-de-grace/pkg/version.buildDate={{ .Date }}
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - ppc64le
      - s390x
archives:
  - id: ttctl-tarball
    builds:
      - ttctl
    replacements:
      386: i386
      amd64: x86_64
    format: tar.gz
  - id: binaries
    builds:
      - manager
      - ttctl
    replacements:
      386: i386
      amd64: x86_64
    format: binary
brews:
  - name: ttctl
    tap:
      owner: Slahser
      name: homebrew-tap
    commit_author:
      name: ttreleasebot
      email: skyslahser@gmail.com
    skip_upload: auto
    folder: Formula
    homepage: https://slahser.com
    description: Interact with KUTTL via the kubectl plugin
    dependencies:
      -
    install: |
      bin.install "ttctl"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: Slahser
    name: ttctl
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
